### ISSUE TITLE
Notification not show when i kill the app 

### ISSUE THREAD

**Issue by zengKun2002** [hippogamesunity/SimpleAndroidNotificationsPublic#35]
Notification not show when i kill the app. But when i make the app run in the background, the notification shows

**Comment by hippogamesunity** [comment]
Hi! System settings, especially energy saving features and apps, may result
this. I would recommend you to test on another device to make sure it's not
plugin issue.

**Comment by zengKun2002** [comment]
hi, work fine in google nexus.  is your plugin require some google plugin support?

**Comment by hippogamesunity** [comment]
No. As I said, some devices have energy saving features that may block notifications for low priority app or just by default. Sometimes you can allow it from their UI. You need to make a research in Google.

**Comment by zengKun2002** [comment]
thank you so much. i will try my best to make a research in Google.

**Comment by Gikerowski** [comment]
@zengKun2002 Did you found any solution for that? 
I have huwawei Mate 20 pro (running android 9) and after killing app notifications are not appearing. 
I also tested older android versions (7 (Samsung s6)  and 8.1 (huwawei  p20 pro) - and everything works fine

Update:
As mentioned before it's because power management. After disabling background app auto management everything works fine!

**Comment by hippogamesunity** [comment]
Nice to hear it, thanks!
