### ISSUE TITLE
Android 12+ Crash : If user turn off SCHEDULE_EXACT_ALARM permission in alarm & reminder setting, the notification will crash!

### ISSUE THREAD

**Issue by qq4848487788** [hippogamesunity/SimpleAndroidNotificationsPublic#90]
We have add the permission to the manifest:

`<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>`

But the user can turn off SCHEDULE_EXACT_ALARM permission in alarm & reminder setting. If the user hasn't granted the permission, the notification will crash:

`java.lang.SecurityException: Caller xxxxxx needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms`

The plugin need to check if the permission was granted by canScheduleExactAlarms before set alarm.

Waiting for a new update! Thanks.

**Comment by hippogamesunity** [comment]
HI! I don't plan to include permissions functionality to the asset (but I'll think about this). You can do this inside Unity if needed:
https://docs.unity3d.com/Manual/android-RequestingPermissions.html

Moreover, this permission is now affected by new restrictions, so you should consider using inexact alarms.
https://developer.android.com/about/versions/12/behavior-changes-12#foreground-service-launch-restrictions
https://developer.android.com/training/scheduling/alarms

BTW, I don't know how additional permissions may affect your app's visibility on Google Play, but I decided to remove exact alarms in all of my apps and games, because actually I don't need exact alarms.

**Comment by qq4848487788** [comment]
Thanks for your reply.

Maybe checking the permission before setting alarm is a more safe way?

And then we can just not request the SCHEDULE_EXACT_ALARM in androidmanifest.xml if we want to remove the exact alarms without crash. 

We have tried not to set notification in our new update version but got lots of crash on android 12 in google play console because old registered notifications trigger the unsafe code.

**Comment by skhirosh** [comment]
How do we specify that our alarm should be exact/inexact? We're calling SendWithAppIcon(), as in the example code. [Update: Am I not seeing it because we're using the free version?]

**Comment by hippogamesunity** [comment]
> How do we specify that our alarm should be exact/inexact? We're calling SendWithAppIcon(), as in the example code. [Update: Am I not seeing it because we're using the free version?]

Right, in the free version you have only inexact alarms.

**Comment by skhirosh** [comment]
Update re. my question: After a brief discussion in Discord, the dev said: "Yes, it looks the free version uses exact alarms, so you need the permission. I'll register this issue for resolution." Thank you!

**Comment by hippogamesunity** [comment]
I've updated both free and paid assets to version 3.2.
The free version now uses only inexact alarms and doesn't require SCHEDULE_EXACT_ALARM permission.
The paid version doesn't include SCHEDULE_EXACT_ALARM permission in AndroidManifest.xml by default (but you can add it if needed) and will request it from C# code with Permission.RequestUserPermission (inside NotificationManager.SendCustom). If the permission is not granted, it will force inexact alarms.
I've also added additional check in Java code (AlarmManager.canScheduleExactAlarms).

Unfortunately, I was unable to test it on my Android 12 device (everything works fine without the permission and you can't even request it). It looks that these crashes occure only on Android 13. I've found the following info:

> The android.permission.SCHEDULE_EXACT_ALARM it's safe to use, on Android 12 this permission is automatically granted by the Android system but on Android 13 you need to check if the user has granted this permission.

https://stackoverflow.com/questions/71031091/android-12-using-schedule-exact-alarm-permission-to-get-show-data-at-specific-t

Please let me know if the problem is now solved.

**Comment by hippogamesunity** [comment]
![image](https://user-images.githubusercontent.com/7318172/199776333-4868ee1c-28f1-4bd0-bd3f-1f7a92435052.png)

**Comment by hippogamesunity** [comment]
And don't forget to write a review on the Asset Store please!
